[build-system]
requires = [
    "setuptools>=64",
    "wheel",
    "cmake>=3.18",
    "pybind11>=2.10"
]
build-backend = "setuptools.build_meta"

[project]
name = "cia-to-cci"
version = "0.1.2"
description = "Python library for converting Nintendo 3DS CIA files to decrypted CCI files"
readme = "README.md"
authors = [
    {name = "Rey Rodrigues"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Programming Language :: C",
]
keywords = ["3ds", "cia", "cci", "ctrtool", "makerom", "nintendo"]

[project.scripts]
cia-to-cci = "cia_to_cci.__main__:main"

[project.urls]
Homepage = "https://github.com/reyrodrigues/cia-to-cci"
Repository = "https://github.com/reyrodrigues/cia-to-cci"

[tool.setuptools.packages.find]
where = ["src"]

[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"
skip = "pp* *-musllinux_* *-win32 *-manylinux_i686"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["x86_64"]
